name: ProjectOpenSpace-Core
version: '${version}'
main: openspacecore.Main
api-version: '1.20'
commands:
  launchrocket:
    description: Launches the rocket
    aliases:
      - lrocket
      - rocket
      - lr
    usage: /<command> <planet> <confirm>
